[logging]
filename = "log"
filemode = "w"
format = "%(levelname)8s %(asctime)10s %(name)s %(module)s:%(lineno)d %(message)s"
datefmt = "%H:%M:%S"
level = "DEBUG"

[provider]
exchanges = ["binance", "okex"]
only_traded = true

[dumps]
filename = "pairs"
